### ISSUE TITLE
unpack requires a buffer 4 bytes

### ISSUE THREAD

**Issue by mdevore300** [adamreeve/npTDMS#272]
My code using TDMS usually works fine. This file got interrupted and restarted with a different index number. But when you TDMSFile.open i get the unpack error

[nptdms.reader WARNING] Last segment of file has unknown size, will attempt to read to the end of the file
Traceback (most recent call last):

  File "P:\Data by Fiscal Year\2022\ER\untitled0.py", line 31, in <module>
    tdms_file = TdmsFile.open("%s_0000.tdms" % name, raw_timestamps = True)

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 87, in open
    return TdmsFile(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 130, in __init__
    self._read_file(self._reader, read_metadata_only, keep_open)

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 226, in _read_file
    tdms_reader.read_metadata(require_segment_indexes=keep_open)

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\reader.py", line 87, in read_metadata
    segment, properties = self._read_segment_metadata(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\reader.py", line 241, in _read_segment_metadata
    properties = segment.read_segment_objects(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms_segment.py", line 103, in read_segment_objects
    raw_data_index_header = _struct_unpack(endianness + 'L', raw_data_index_header_bytes)[0]

error: unpack requires a buffer of 4 bytes

**Comment by adamreeve** [comment]
Hi, thanks for the bug report. It looks like the current logic for trying to read the last segment when writing was interrupted is assuming that the metadata was written okay and the data segment might be truncated, but doesn't account for cases where the segment metadata was not fully written.

**Comment by adamreeve** [comment]
Hi @mdevore300, I've just pushed a fix for this in #273, are you able to test with the current master branch of the code to see if your file can now be read?

**Comment by adamreeve** [comment]
Hmm okay I'm not sure what's going on there, are you able to provide a copy of the TDMS file that reproduces the error?

**Comment by mdevore300** [comment]
Sure.

From: Adam Reeve ***@***.***>
Sent: Wednesday, June 15, 2022 12:53 PM
To: adamreeve/npTDMS ***@***.***>
Cc: DeVore II, Michael Alan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adamreeve/npTDMS] unpack requires a buffer 4 bytes (Issue #272)


Hmm okay I'm not sure what's going on there, are you able to provide a copy of the TDMS file that reproduces the error?

**Comment by mdevore300** [comment]
Also got this error with a different file requiring 20 bytes

Traceback (most recent call last):

  File "<ipython-input-36-975b851b8107>", line 1, in <module>
    test = TdmsFile.open("2PMR060622_0000.tdms")

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 87, in open
    return TdmsFile(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 130, in __init__
    self._read_file(self._reader, read_metadata_only, keep_open)

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\tdms.py", line 226, in _read_file
    tdms_reader.read_metadata(require_segment_indexes=keep_open)

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\reader.py", line 87, in read_metadata
    segment, properties = self._read_segment_metadata(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\reader.py", line 235, in _read_segment_metadata
    (position, toc_mask, data_position, next_segment_pos, segment_incomplete) = self._read_lead_in(

  File "C:\Users\284210\Anaconda3\lib\site-packages\nptdms-1.3.1-py3.8.egg\nptdms\reader.py", line 268, in _read_lead_in
    (version, next_segment_offset, raw_data_offset) = _struct_unpack(endianness + 'lQQ', lead_in_bytes[8:28])

error: unpack requires a buffer of 20 bytes

From: Adam Reeve ***@***.***>
Sent: Wednesday, June 15, 2022 12:53 PM
To: adamreeve/npTDMS ***@***.***>
Cc: DeVore II, Michael Alan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adamreeve/npTDMS] unpack requires a buffer 4 bytes (Issue #272)


Reopened #272<https://urldefense.com/v3/__https:/github.com/adamreeve/npTDMS/issues/272__;!!Bt8fGhp8LhKGRg!DefUfUWxohNFHVp4obIUrDPkB3tOpiWusqruxGtKlmNN2j_H-XkKQ4wdIIGM6DeqBEC7PD5OojOBqDyT_18OqDiB43IhCg$>.

**Comment by adamreeve** [comment]
Sorry I'm guessing you've sent the files as email attachments but it doesn't look like GitHub adds them to the issue, you could send them directly to me at adreeve@gmail.com.

**Comment by adamreeve** [comment]
We've confirmed this is fixed but just updating the source files wasn't enough to pick up the fix. The fix has been released in version 1.5.0.

**Comment by strontium5** [comment]
I'm using release 1.5.0, but still getting this same error:
`
line 103, in read_segment_objects
    raw_data_index_header = _struct_unpack(endianness + 'L', raw_data_index_header_bytes)[0]
struct.error: unpack requires a buffer of 4 bytes
`

**Comment by adamreeve** [comment]
Hi @strontium5, are you able to provide an example file that reproduces the problem?

**Comment by mdevore300** [comment]
I will give it a try this morning. Do I need to update the package somehow?

From: Adam Reeve ***@***.***>
Sent: Sunday, June 12, 2022 3:57 PM
To: adamreeve/npTDMS ***@***.***>
Cc: DeVore II, Michael Alan ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [adamreeve/npTDMS] unpack requires a buffer 4 bytes (Issue #272)


Hi @mdevore300<https://urldefense.com/v3/__https:/github.com/mdevore300__;!!Bt8fGhp8LhKGRg!G63lnRfXPDtD2k1Y2aWaQHYmsFrvaNeft-H3v6jUosCkqOcMMgXDOimDxoZ8oCJQ7uGbld0dV-YiNMTh-h2v4j1J4avGkw$>, I've just pushed a fix for this in #273<https://urldefense.com/v3/__https:/github.com/adamreeve/npTDMS/pull/273__;!!Bt8fGhp8LhKGRg!G63lnRfXPDtD2k1Y2aWaQHYmsFrvaNeft-H3v6jUosCkqOcMMgXDOimDxoZ8oCJQ7uGbld0dV-YiNMTh-h2v4j1_G2B3Eg$>, are you able to test with the current master branch of the code to see if your file can now be read?

**Comment by hnphien** [comment]
Hi @adamreeve ,
I am using nptdms for extracting data from a TDMS file with 50MB, I am facing with this issue:
`Traceback (most recent call last):
  File "C:\Users\hnphien\Documents\converter\program.py", line 64, in <module>
    run(log=proc_logger, config=proc_config)
  File "C:\Users\hnphien\Documents\converter\program.py", line 40, in run
    try_convert(
  File "C:\Users\hnphien\Documents\converter\src\ft_converter\convert.py", line 60, in try_convert
    dataframes = _convert(
  File "C:\Users\hnphien\Documents\converter\src\ft_converter\convert.py", line 42, in _convert
    df_hys = process_tdms(log, file_path, cache_file_path)
  File "C:\Users\hnphien\Documents\converter\src\ft_converter\tdms_processor\tdms_process.py", line 27, in process_tdms
    tdms: TdmsFile = TdmsFile(file_path)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms.py", line 131, in __init__
    self._read_file(self._reader, read_metadata_only, keep_open)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms.py", line 289, in _read_file
    self._read_data(tdms_reader)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms.py", line 301, in _read_data
    for chunk in tdms_reader.read_raw_data():
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\reader.py", line 119, in read_raw_data
    for chunk in segment.read_raw_data(self._file):
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms_segment.py", line 244, in read_raw_data
    for chunk in self._read_data_chunks(f, data_objects, self.num_chunks):
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms_segment.py", line 359, in _read_data_chunks
    for chunk in reader.read_data_chunks(file, data_objects, num_chunks):
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\base_segment.py", line 52, in read_data_chunks
    yield self._read_data_chunk(file, data_objects, chunk)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms_segment.py", line 482, in _read_data_chunk
    object_data[obj.path] = obj.read_values(file, number_values, self.endianness)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\tdms_segment.py", line 562, in read_values
    return self.data_type.read_values(file, number_values, endianness)
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\types.py", line 219, in read_values
    offsets.append(Uint32.read(file, endianness))
  File "c:\Users\hnphien\.conda\envs\wlt\lib\site-packages\nptdms\types.py", line 98, in read
    return _struct_unpack(endianness + cls.struct_declaration, read_bytes)[0]
struct.error: unpack requires a buffer of 4 bytes`
I am using npTDMS==1.6.2, could you please help me with that?
Hope for you response.
Thank you so much.

**Comment by ba05** [comment]
I'm still having this issue with version 1.9.0.

**Comment by adamreeve** [comment]
Hi @ba05, if you can email me an example file that reproduces the error I can take a look.
