### ISSUE TITLE
FutureWarning: from_items is deprecated

### ISSUE THREAD

**Issue by ba05** [adamreeve/npTDMS#92]
I get this warning:

`FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.`

**Comment by adamreeve** [comment]
Thanks for reporting this, this is now fixed in version 0.12.0

**Comment by joans** [comment]
Hi, this issue is still existent in Windows 10, Python 3.7 64bit
![image](https://user-images.githubusercontent.com/1465851/59836319-97caee80-934b-11e9-8987-cfa390c9a2ee.png)

**Comment by adamreeve** [comment]
Looks like I missed another place where this was used, this is now fixed in 0.15.1.
